import { prisma } from '../../config/database';
import { DocumentCategory, DocumentPermission, Prisma } from '@prisma/client';

export const documentsService = {
  async uploadDocument(userId: string, data: {
    name: string;
    category: DocumentCategory;
    fileUrl: string;
    fileType: string;
    fileSize: number;
    tenancyId?: string;
    permission?: DocumentPermission;
    expiryDate?: Date;
  }) {
    const document = await prisma.document.create({
      data: {
        userId,
        ...data,
        isAutoGenerated: false
      }
    });

    // Trigger mock OCR for specific categories
    if (data.category === 'KYC' || data.category === 'AGREEMENTS') {
      return this.simulateOcr(document.id);
    }

    return document;
  },

  async simulateOcr(documentId: string) {
    const document = await prisma.document.findUnique({ where: { id: documentId } });
    if (!document) throw new Error('Document not found');

    // Simulate delay and extraction logic
    let ocrMetadata: any = {};
    if (document.category === 'KYC') {
      ocrMetadata = {
        id_type: 'PASSPORT',
        id_number: `PN-${Math.floor(100000 + Math.random() * 900000)}`,
        full_name: 'SIMULATED DATA',
        extracted_at: new Date().toISOString()
      };
    } else if (document.category === 'AGREEMENTS') {
      ocrMetadata = {
        contract_value: 1500,
        currency: 'USD',
        start_date: '2026-01-01',
        end_date: '2027-01-01'
      };
    }

    return prisma.document.update({
      where: { id: documentId },
      data: {
        ocrMetadata,
        expiryDate: document.category === 'KYC' ? new Date(Date.now() + 365 * 24 * 60 * 60 * 1000) : undefined
      }
    });
  },

  async listDocuments(userId: string, filters: {
    category?: DocumentCategory;
    tenancyId?: string;
    q?: string;
  }) {
    // Permission logic:
    // 1. Owner can always see.
    // 2. If TENANT_LANDLORD or ALL_PARTIES, check if current user is part of the linked tenancy.
    
    // First, find all tenancies the user is part of (as tenant or landlord)
    const userTenancies = await prisma.tenancy.findMany({
      where: {
        OR: [
          { tenantId: userId },
          { property: { ownerId: userId } }
        ]
      },
      select: { id: true }
    });
    const tenancyIds = userTenancies.map(t => t.id);

    const where: Prisma.DocumentWhereInput = {
      AND: [
        {
          OR: [
            { userId: userId }, // Owner
            {
              AND: [
                { tenancyId: { in: tenancyIds } },
                { permission: { in: ['TENANT_LANDLORD', 'ALL_PARTIES', 'PUBLIC'] } }
              ]
            },
            { permission: 'PUBLIC' }
          ]
        },
        filters.category ? { category: filters.category } : {},
        filters.tenancyId ? { tenancyId: filters.tenancyId } : {},
        filters.q ? { name: { contains: filters.q, mode: 'insensitive' } } : {}
      ]
    };

    return prisma.document.findMany({
      where,
      orderBy: { createdAt: 'desc' }
    });
  },

  async deleteDocument(userId: string, documentId: string) {
    const doc = await prisma.document.findUnique({ where: { id: documentId } });
    if (!doc) throw new Error('Document not found');
    if (doc.userId !== userId) throw new Error('Access denied');

    return prisma.document.delete({ where: { id: documentId } });
  },

  async getExpiryAlerts(userId: string) {
    const thirtyDaysFromNow = new Date();
    thirtyDaysFromNow.setDate(thirtyDaysFromNow.getDate() + 30);

    return prisma.document.findMany({
      where: {
        userId,
        expiryDate: {
          gt: new Date(),
          lte: thirtyDaysFromNow
        }
      },
      orderBy: { expiryDate: 'asc' }
    });
  },

  // Called by other modules to "Auto-File" system generated documents
  async registerSystemDocument(data: {
    userId: string;
    tenancyId?: string;
    category: DocumentCategory;
    name: string;
    fileUrl: string;
    fileType: string;
    fileSize: number;
    permission: DocumentPermission;
  }) {
    return prisma.document.create({
      data: {
        ...data,
        isAutoGenerated: true
      }
    });
  }
};