export const MODULES = {
  PROPERTY: 'PROPERTY',
  VISIT: 'VISIT',
  AGREEMENT: 'AGREEMENT',
  KYC: 'KYC',
  SLAAS: 'SLAAS',
  SMART_AGREEMENT: 'SMART_AGREEMENT',
  LOCAL_EXPERT: 'LOCAL_EXPERT',
  MAINTENANCE: 'MAINTENANCE',
  PAYMENT_VAULT: 'PAYMENT_VAULT',
  DISPUTE: 'DISPUTE',
  SUPPORT_HUB: 'SUPPORT_HUB',
  DG_NOTICEBOARD: 'DG_NOTICEBOARD',
  MY_SOCIETY: 'MY_SOCIETY',
  DOCUMENTS: 'DOCUMENTS',
  MOVE_IN: 'MOVE_IN',
  EXIT: 'EXIT',
} as const;

export type ModuleName = typeof MODULES[keyof typeof MODULES];

export const FEATURES = {
  // Property features
  CREATE_PROPERTY: 'CREATE_PROPERTY',
  VIEW_PROPERTY: 'VIEW_PROPERTY',
  UPDATE_PROPERTY: 'UPDATE_PROPERTY',
  DELETE_PROPERTY: 'DELETE_PROPERTY',

  // Visit features
  REQUEST_VISIT: 'REQUEST_VISIT',
  APPROVE_VISIT: 'APPROVE_VISIT',

  // Agreement features
  CREATE_AGREEMENT: 'CREATE_AGREEMENT',
  VIEW_AGREEMENT: 'VIEW_AGREEMENT',

  // KYC features
  SUBMIT_KYC: 'SUBMIT_KYC',
  VERIFY_KYC: 'VERIFY_KYC',
  VIEW_KYC_STATUS: 'VIEW_KYC_STATUS',

  // SLAAS features
  ACCESS_SLAAS: 'ACCESS_SLAAS',

  // Smart Agreement features
  CREATE_SMART_AGREEMENT: 'CREATE_SMART_AGREEMENT',
  SIGN_AGREEMENT: 'SIGN_AGREEMENT',

  // Local Expert features
  HIRE_EXPERT: 'HIRE_EXPERT',
  VIEW_EXPERTS: 'VIEW_EXPERTS',

  // Maintenance features
  REQUEST_MAINTENANCE: 'REQUEST_MAINTENANCE',
  APPROVE_MAINTENANCE: 'APPROVE_MAINTENANCE',

  // Payment Vault features
  ACCESS_PAYMENT_VAULT: 'ACCESS_PAYMENT_VAULT',
  MAKE_PAYMENT: 'MAKE_PAYMENT',

  // Dispute features
  RAISE_DISPUTE: 'RAISE_DISPUTE',
  RESOLVE_DISPUTE: 'RESOLVE_DISPUTE',

  // Support Hub features
  ACCESS_SUPPORT: 'ACCESS_SUPPORT',

  // DG NoticeBoard features
  VIEW_NOTICES: 'VIEW_NOTICES',
  POST_NOTICE: 'POST_NOTICE',

  // My Society features
  MANAGE_SOCIETY: 'MANAGE_SOCIETY',
  VIEW_SOCIETY_MEMBERS: 'VIEW_SOCIETY_MEMBERS',

  // Documents features
  UPLOAD_DOCUMENT: 'UPLOAD_DOCUMENT',
  VIEW_DOCUMENTS: 'VIEW_DOCUMENTS',

  // Move-in features
  INITIATE_MOVE_IN: 'INITIATE_MOVE_IN',

  // Exit features
  INITIATE_EXIT: 'INITIATE_EXIT',
} as const;

export type FeatureName = typeof FEATURES[keyof typeof FEATURES];
